apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: toxic-detection
  namespace: researchai
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: sa-minio-kserve
    tensorflow:
    resources:
        limits:
          cpu: '1'
          memory: 2Gi
          nvidia.com/mig-1g.5gb: '1'
        requests:
          cpu: '1'
          memory: 2Gi
          nvidia.com/mig-1g.5gb: '1'
      storageUri: s3://mlpipeline/models/detect-digits/
      runtimeVersion: 2.8.0